### ISSUE TITLE
Test with windows

### ISSUE THREAD

**Issue by yajamon** [ingoose/ingoose#2]
### 現状

``` bash
$ npm test

> ingoose@0.0.1 test C:\Git\ingoose
> gulp test; ./node_modules/testem/testem.js launchers; ./node_modules/testem/testem.js

[11:24:24] Requiring external module coffee-script/register
[11:24:25] Using gulpfile C:\Git\ingoose\gulpfile.coffee
[11:24:25] Task 'test;' is not in your gulpfile
[11:24:25] Please check the documentation for proper gulpfile formatting
npm ERR! Test failed.  See above for more details.
```
### 対応

Windowsでも実行できると嬉しいので対応を考えています。

以下を参考にして進めます
- [npm で依存もタスクも一元化する - Qiita](http://qiita.com/Jxck_/items/efaff21b977ddc782971)

**Comment by otiai10** [comment]
Windowsだとこれ具体的にどこがこけてるんですか？

**Comment by otiai10** [comment]
`test;`をtaskとして認識できてないような気がするんですが、package.jsonを

``` json
{
    "scripts": {
        "pretest": "gulp test",
        "test": "./node_modules/testem/testem.js"
    }
}
```

にするだけで直ったりしませんかね...

![2015-2-9-15-18-49](https://cloud.githubusercontent.com/assets/931554/6101866/07d98138-b06f-11e4-8234-4d8718805ccc.png)

**Comment by yajamon** [comment]
セミコロンが文の区切りにならないために、"task;"というタスクを探してこけてます。

**Comment by yajamon** [comment]
> test;をtaskとして認識できてないような気がするんですが、package.jsonを
> 
> ``` json
> {
>     "scripts": {
>         "pretest": "gulp test",
>         "test": "./node_modules/testem/testem.js"
>     }
> }
> ```
> 
> にするだけで直ったりしませんかね...

治りますよ！

**Comment by yajamon** [comment]
誤って閉じてしまいました。。。

**Comment by otiai10** [comment]
lauchersはこの際いらないっすよね

**Comment by yajamon** [comment]
そうですねー。別途確認する手段はありますし。

**Comment by yajamon** [comment]
あと、パス区切り文字の違いによって、以下のエラーが起きます。
窓の闇っすね…。

```
> ingoose@0.0.1 test C:\git\ingoose
> ./node_modules/testem/testem.js launchers; ./node_modules/testem/testem.js

'.' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
npm ERR! Test failed.  See above for more details.
```

ただ、こちらは以下の形で問題ないです。

``` json
{
    "scripts": {
        "test": "testem"
    }
}
```

**Comment by otiai10** [comment]
グローバルにtestemが無い場合でも、testemって言ったらローカルのnode_modules見ます？

もし見るならよし、見れないなら、プロジェクトのrequirementに`npm install -g testem`を加える必要がある気がします。

![5ij](https://cloud.githubusercontent.com/assets/931554/6101996/7224e2f6-b071-11e4-8d16-0ee8e9280327.jpg)

**Comment by yajamon** [comment]
npm run hoge で実行した場合、 プロジェクトのnode_module を見に行くので問題ないです！
私グローバルにgulp入れてないのですが `npm test`から `gulp test`が実行されてます。

**Comment by otiai10** [comment]
oh... wonderful npm scripts.

**Comment by yajamon** [comment]
すっごくオシリ支えられてます

**Comment by otiai10** [comment]
![](http://img.tiqav.com/2xK.jpg)

**Comment by yajamon** [comment]
挿すならnpmの旦那にｵﾅｼｬｽ!

**Comment by otiai10** [comment]
![](http://livedoor.blogimg.jp/sumomo3986/imgs/1/d/1d081096.png)

**Comment by yajamon** [comment]
ｻｰｾﾝ...

**Comment by yajamon** [comment]
windowsで実施できるようなので、対応してPullReqしようと思ってます。

**Comment by otiai10** [comment]
#4
