### ISSUE TITLE
DemoがFirefoxで動作できないようです。

### ISSUE THREAD

**Issue by ghost** [ingoose/ingoose#5]
「indexedDB.webkitGetDatabaseNamesが関数ではありません」というエラーが出ています。

この関数はChrome独自定義のものとは分かりますが、このライブラリはChrome専用なのですか？

**Comment by yajamon** [comment]
https://github.com/ingoose/ingoose/blob/master/demo.html#L20

当該の処理はDemo用のコードになります。
ingoose というより、 Demoが chrome でのみ動作する状態ですね。

**Comment by otiai10** [comment]
Thanks, @yajamon !

**Comment by yajamon** [comment]
No problem !
